name: "food-api multistage build and test using templates"

variables:
  dotnetSdkVersion: "5.x"
  buildConfiguration: "Release"
  releaseBranchName: "master"
  apifolder: "FoodApi"
  apitestfolder: "FoodApiTest"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - $(apifolder)

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "Build"
        displayName: "Build job"

        steps:
          - template: templates/netcore-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(apifolder)

  - stage: "Test"
    displayName: "Test"
    dependsOn: Build

    jobs:
      - job: test_dotnet_solution
        displayName: test dotnet solution

        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              projects: "apitestfolder/*.csproj"
              arguments: "--configuration $(buildConfiguration)"
